/*

 NIVEL1OBJS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 16
   Tile set      : C:\gbdk\examples\gb\Ejemplo1\Mapa.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Nivel1objsLabelWidth 32
#define Nivel1objsLabelHeight 16
#define Nivel1objsLabelBank 0

extern unsigned char Nivel1objsLabel[];

/* End of NIVEL1OBJS.H */
