/*

 NIVEL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 16
   Tile set      : Mapa.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Nivel2LabelWidth 32
#define Nivel2LabelHeight 16
#define Nivel2LabelBank 0

extern unsigned char Nivel2Label[];

/* End of NIVEL2.H */
