/*

 NIVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 16
   Tile set      : C:\gbdk\examples\gb\Ejemplo1\Mapa.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Nivel1LabelWidth 32
#define Nivel1LabelHeight 16
#define Nivel1LabelBank 0

extern unsigned char Nivel1Label[];

/* End of NIVEL1.H */
